services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_DB: jobapp
      POSTGRES_USER: xaxage
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge